### ISSUE TITLE
Similar awesome list?

### ISSUE THREAD

**Issue by zhimin-z** [Renumics/awesome-open-data-centric-ai#4]
This is definitely an awesome list, however, I notice there exist two similar list that might need our attention:
https://github.com/Data-Centric-AI-Community/awesome-data-centric-ai
https://github.com/HazyResearch/data-centric-ai

How do we differentiate the list from each other in terms of the goal?

**Comment by ssuwelack** [comment]
Thank you very much for asking this. We thought a lot about how to avoid duplicate work. We want to list stuff that falls into these categories (see the scope section):
1. Tools are open source and actively maintained
2. Tools are useful for unstructured data
3. Tools are ready for real-world use cases
4. Not a labeling tool

The first link you mentioned focuses mainly on tabular and time series data, I had already included a link to this cool list by ydata. 

The hazy research list is less focussed on tools and more on background info and research papers. I just added a link to this list, as it might be interesting for many readers of this list.

I hope the "scope" section is more complete now. Thank you very much for your feedback!
